version: '3.1'
services:
  postgres-app:
    image: "postgres:9.6-alpine"
    container_name: postgres-app
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db_scpa
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  adminer:
    image: "library/adminer:4.8.1"
    container_name: adminer
    depends_on:
      - postgres-app
    ports:
      - 9000:8080
  scpa-app:
    build: ./
    container_name: scpa-app
    depends_on:
      - postgres-app
    environment:
      - DB_SERVER=postgres-app
      - POSTGRES_DB=db_scpa
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 8080:8080