server:
  port: 8080

spring:
  profiles:
    active: development

---
spring:
  config:
    activate:
      on-profile: development
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_scpa
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_SERVER}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    jpa:
      show-sql: false
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      generate-ddl: true
      hibernate:
        ddl-auto: update